version: '3.8'

services:
  arclight:
    container_name: mc-arclight
    build: .
    ports:
      - "25565:25565"
    volumes:
      - .:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
