[spawn]
	#Set true to allow Senpai to spawn naturally
	spawn_senpai = false
	#this feature is under development, DO NOT TURN THIS ON!
	spawn_mob_with_guns = false

[projectile]
	#Set true to allow projectiles to destroy certain blocks
	allow_projectile_destroy_blocks = false

[explosion]
	#The percentage of explosion damage you take behind cover
	# Default: 15
	# Range: 0 ~ 100
	explosion_penetration_ratio = 15
	#Set true to allow Explosion to destroy blocks
	explosion_destroy = true
	#Set true to enable extra explosion effect. For example, C4 and RPG will destroy blocks before explosion
	extra_explosion_effect = true

	[explosion."RGO Grenade"]
		#The explosion damage of RGO grenade
		# Default: 90
		# Range: 1 ~ 10000000
		rgo_grenade_explosion_damage = 90
		#The explosion radius of RGO grenade
		# Default: 5
		# Range: 1 ~ 50
		rgo_grenade_explosion_radius = 5

	[explosion."M67 Grenade"]
		#The explosion damage of M67 grenade
		# Default: 120
		# Range: 1 ~ 10000000
		m67_grenade_explosion_damage = 120
		#The explosion radius of M67 grenade
		# Default: 6
		# Range: 1 ~ 50
		m67_grenade_explosion_radius = 6

	[explosion.C4]
		#The explosion damage of C4
		# Default: 300
		# Range: > 1
		c4_explosion_damage = 300
		#The explosion countdown of C4
		# Default: 514
		# Range: > 1
		c4_explosion_countdown = 514
		#The explosion radius of C4
		# Default: 10
		# Range: > 1
		c4_explosion_radius = 10

	[explosion.Claymore]
		#The explosion damage of Claymore
		# Default: 140
		# Range: > 1
		claymore_explosion_damage = 140
		#The explosion radius of Claymore
		# Default: 4
		# Range: > 1
		claymore_explosion_radius = 4

[vehicle]
	#Allow vehicles to pick up items
	vehicle_item_pickup = true
	#Allow vehicles to collect drops after killing other entities by crashing
	collect_drops_by_crashing = true
	#Within this distance, the vehicle info will be displayed at client side
	# Default: 512
	# Range: 0 ~ 1024
	vehicle_info_display_distance = 512
	#The damage of self explosion when a vehicle is destroyed
	# Default: 114514
	# Range: > 0
	self_explosion_damage = 114514
	#The damage count of self explosion when a vehicle is destroyed
	# Default: 5
	# Range: 0 ~ 100
	self_explosion_count = 5
	#The air crash damage when an aircraft is destroyed
	# Default: 114514
	# Range: > 0
	air_crash_explosion_damage = 114514
	#The air crash damage count when an aircraft is destroyed
	# Default: 5
	# Range: 0 ~ 100
	air_crash_explosion_count = 5

	[vehicle.collision]
		#Allows vehicles to destroy soft blocks via collision
		collision_destroy_soft_blocks = false
		#Allows vehicles to destroy normal blocks via collision
		collision_destroy_normal_blocks = false
		#Allows vehicles to destroy hard blocks via collision
		collision_destroy_hard_blocks = false
		#Allows vehicles to destroy blocks via collision like a beast
		collision_destroy_blocks_beastly = false
		#List of entities that can be damaged by collision
		collision_entity_whitelist = []

	[vehicle.repair]
		#The default cooldown of vehicle repair. Set a negative value to disable vehicle repair
		# Default: 200
		# Range: -1 ~ 100000000
		repair_cooldown = 200
		#The default amount of health restored per tick when a vehicle is self-repairing
		# Default: 0.05
		# Range: -1.0E8 ~ 1.0E8
		repair_amount = 0.05

[misc]
	#Set true to enable tactical sprint
	allow_tactical_sprint = false
	#Set true to enable kill feedback sending
	send_kill_feedback = true
	#Set true to enable force damage
	allow_force_damage = false
	#Whether to drop an ammo box after the player dies
	drop_ammo_box = false
	#The default maximum armor level for normal armors
	# Default: 1
	# Range: 0 ~ 10000000
	default_armor_level = 1
	#The maximum armor level for armors with superbwarfare:military_armor tag
	# Default: 2
	# Range: 0 ~ 10000000
	military_armor_level = 2
	#The maximum armor level for armors with superbwarfare:military_armor_heavy tag(will override superbwarfare:military_armor tag!)
	# Default: 3
	# Range: 0 ~ 10000000
	heavy_military_armor_level = 3
	#The points per level for armor plate
	# Default: 15
	# Range: 0 ~ 10000000
	armor_point_per_level = 15
	#Max energy storage of charging station
	# Default: 4000000
	# Range: > 1
	charging_station_max_energy = 4000000
	#How much FE energy can charging station generate per tick
	# Default: 128
	# Range: > 1
	charging_station_generate_speed = 128
	#How much FE energy can charging station transfer per tick
	# Default: 100000
	# Range: > 1
	charging_station_transfer_speed = 100000
	#The charging radius of the charging station
	# Default: 8
	# Range: 0 ~ 128
	charging_station_charge_radius = 8
	#The default fuel time of the charging station
	# Default: 1600
	# Range: > 1
	charging_station_default_fuel_time = 1600
	#The max size of artillery indicator binding list
	# Default: 32
	# Range: > 1
	artillery_indicator_list_size = 32
	#Set true to make mine hitbox invisible
	mine_hitbox_invisible = false
	#Set true to allow smoke to prevent entities from being set as target
	smoke_hide_target = false
